services:
  monero-lws:
    # depends_on:
    #   - monero
    container_name: monero-lws
    build:
      context: .
    restart: always
    ports:
      - 8443:8443
    command:
      - --db-path=/home/monero-lws/.bitmonero/light_wallet_server
      - --daemon=tcp://monero:1882
      - --sub=tcp://monero:18084
      - --zmq-pub=tcp://monero:18084
      - --log-level=4
      - --webhook-ssl-verification=none
      - --disable-admin-auth
      - --admin-rest-server=http://0.0.0.0:8443/admin
      - --rest-server=http://0.0.0.0:8443/basic
      - --access-control-origin=lws:8443
      - --confirm-external-bind
    volumes:
      - monerolws:/home/monero-lws
    networks:
      - monerolws

volumes:
  monerolws: {}

networks:
  monerolws:
    driver: bridge
