name: Build+Push Daemon/Admin Docker Image

on:
  push:
    branches: [ "release-v1.0_0.18" ]
    paths-ignore: [ "docs/**", "mkdocs.yml" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Build Docker image
      run: docker build --no-cache --tag vtnerd/monero-lws:1.0 .
    - name: Add additional tags
      run: >
        docker image tag vtnerd/monero-lws:1.0 vtnerd/monero-lws:1 &&
        docker image tag vtnerd/monero-lws:1.0 ghcr.io/vtnerd/monero-lws:1.0 &&
        docker image tag vtnerd/monero-lws:1.0 ghcr.io/vtnerd/monero-lws:1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v4
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push to GitHub Container Registry
      run: docker push -a ghcr.io/vtnerd/monero-lws

    - name: Login to Docker.io
      uses: docker/login-action@v4
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_VTNERD_TOKEN }}
    - name: Push to Docker.io
      run: docker push -a vtnerd/monero-lws
