name: Build+Push Daemon/Admin Docker Image

on:
  push:
    branches: [ "master" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: docker build --no-cache --tag vtnerd/monero-lws:master .
    - name: Add additional tags
      run: docker image tag vtnerd/monero-lws:master ghcr.io/vtnerd/monero-lws:master

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push to GitHub Container Registry
      run: docker push -a ghcr.io/vtnerd/monero-lws

    - name: Login to Docker.io
      uses: docker/login-action@v3
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_VTNERD_TOKEN }}
    - name: Push to Docker.io
      run: docker push -a vtnerd/monero-lws
