name: Build+Push Daemon/Admin Docker Image

on:
  push:
    branches: [ "master" ]
    paths-ignore: [ "docs/**", "mkdocs.yml" ]
    tags: ["*"]

jobs:
  build_and_push:
    strategy:
      matrix:
        platform: [ubuntu-latest, ubuntu-26.04-arm]
    runs-on: ${{matrix.platform}}

    steps:
    - uses: actions/checkout@v6

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v4
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Login to Docker.io
      uses: docker/login-action@v4
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_VTNERD_TOKEN }}

    - name: Build and push Docker image
      run: >
        docker build --no-cache --push
        --tag vtnerd/monero-lws:${{ github.ref_name }}
        --tag ghcr.io/vtnerd/monero-lws:${{ github.ref_name }}
        .
